
[Client]
  Bps = 0
  InsecureSkipVerify = true
  MaxIdleConnsPerHost = 1024
  Proxy = ""

[Scinario]
  Count = 3
  Interval = "3s"
  RampUp = "100ms"
  Worker = 3

[Target]
  Url = "https://ogisui.azurewebsites.net"
